-- PULSE applies this idempotent schema automatically at startup when DATABASE_URL is set.
-- Kept as a standalone migration for Supabase SQL Editor deployments.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS watchlists (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,name));
CREATE TABLE IF NOT EXISTS watchlist_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), watchlist_id uuid NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE, symbol varchar(20) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(watchlist_id,symbol));
CREATE TABLE IF NOT EXISTS market_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, symbol varchar(20) NOT NULL, price numeric(14,2) NOT NULL, volume bigint, volatility numeric(10,4), observed_at timestamptz NOT NULL DEFAULT now(), market_updated_at timestamptz NOT NULL, source text NOT NULL, freshness_status text NOT NULL CHECK(freshness_status IN ('fresh','stale','unavailable')));
CREATE INDEX IF NOT EXISTS market_snapshots_user_symbol_time ON market_snapshots(user_id,symbol,observed_at DESC);
CREATE TABLE IF NOT EXISTS change_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, symbol varchar(20) NOT NULL, previous_snapshot_id uuid REFERENCES market_snapshots(id) ON DELETE SET NULL, current_snapshot_id uuid REFERENCES market_snapshots(id) ON DELETE SET NULL, price_change numeric(14,2), percentage_change numeric(10,4), volume_change numeric(10,4), volatility_change numeric(10,4), change_score integer NOT NULL CHECK(change_score BETWEEN 0 AND 100), significance_level text NOT NULL CHECK(significance_level IN ('NORMAL','MODERATE','SIGNIFICANT')), explanation text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS change_events_user_symbol_time ON change_events(user_id,symbol,created_at DESC);
