import { Pool, type PoolClient } from 'pg';
import type { Change, Quote } from './domain.js';

export const schema = `
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS watchlists (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL DEFAULT 'My watchlist', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,name));
CREATE TABLE IF NOT EXISTS watchlist_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), watchlist_id uuid NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE, symbol varchar(20) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(watchlist_id,symbol));
CREATE TABLE IF NOT EXISTS market_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, symbol varchar(20) NOT NULL, price numeric(14,2) NOT NULL, volume bigint, volatility numeric(10,4), observed_at timestamptz NOT NULL DEFAULT now(), market_updated_at timestamptz NOT NULL, source text NOT NULL, freshness_status text NOT NULL CHECK(freshness_status IN ('fresh','stale','unavailable')));
CREATE INDEX IF NOT EXISTS market_snapshots_user_symbol_time ON market_snapshots(user_id,symbol,observed_at DESC);
CREATE TABLE IF NOT EXISTS change_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, symbol varchar(20) NOT NULL, previous_snapshot_id uuid REFERENCES market_snapshots(id) ON DELETE SET NULL, current_snapshot_id uuid REFERENCES market_snapshots(id) ON DELETE SET NULL, price_change numeric(14,2), percentage_change numeric(10,4), volume_change numeric(10,4), volatility_change numeric(10,4), change_score integer NOT NULL CHECK(change_score BETWEEN 0 AND 100), significance_level text NOT NULL CHECK(significance_level IN ('NORMAL','MODERATE','SIGNIFICANT')), explanation text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS change_events_user_symbol_time ON change_events(user_id,symbol,created_at DESC);`;

type User={id:string;email:string;passwordHash:string};
function rowQuote(r:any):Quote{return {symbol:r.symbol,name:r.name??r.symbol,price:Number(r.price),volume:r.volume===null?undefined:Number(r.volume),volatility:r.volatility===null?undefined:Number(r.volatility),updatedAt:new Date(r.market_updated_at).toISOString(),status:r.freshness_status};}
export class PostgresRepository {
  pool:Pool; constructor(url:string){this.pool=new Pool({connectionString:url,ssl:process.env.PGSSL==='false'?false:{rejectUnauthorized:false}})}
  async migrate(){await this.pool.query(schema)} async close(){await this.pool.end()}
  async createUser(email:string,passwordHash:string):Promise<User>{const r=await this.pool.query('INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id,email,password_hash',[email,passwordHash]);return {id:r.rows[0].id,email:r.rows[0].email,passwordHash:r.rows[0].password_hash}}
  async findUser(email:string):Promise<User|undefined>{const r=await this.pool.query('SELECT id,email,password_hash FROM users WHERE email=$1',[email]);return r.rowCount?{id:r.rows[0].id,email:r.rows[0].email,passwordHash:r.rows[0].password_hash}:undefined}
  async defaultWatchlist(userId:string){const r=await this.pool.query("INSERT INTO watchlists(user_id,name) VALUES($1,'My watchlist') ON CONFLICT(user_id,name) DO UPDATE SET updated_at=watchlists.updated_at RETURNING id,name",[userId]);return r.rows[0]}
  async listWatchlists(userId:string){const r=await this.pool.query('SELECT id,name,created_at,updated_at FROM watchlists WHERE user_id=$1 ORDER BY created_at',[userId]);return r.rows}
  async createWatchlist(userId:string,name:string){const r=await this.pool.query('INSERT INTO watchlists(user_id,name) VALUES($1,$2) RETURNING id,name,created_at,updated_at',[userId,name]);return r.rows[0]}
  async deleteWatchlist(userId:string,id:string){return (await this.pool.query('DELETE FROM watchlists WHERE id=$1 AND user_id=$2',[id,userId])).rowCount!>0}
  async addItem(userId:string,watchlistId:string,symbol:string){const r=await this.pool.query('INSERT INTO watchlist_items(watchlist_id,symbol) SELECT id,$3 FROM watchlists WHERE id=$1 AND user_id=$2 ON CONFLICT(watchlist_id,symbol) DO NOTHING RETURNING id',[watchlistId,userId,symbol]);return Boolean(r.rowCount)}
  async removeItem(userId:string,watchlistId:string,symbol:string){const r=await this.pool.query('DELETE FROM watchlist_items i USING watchlists w WHERE i.watchlist_id=w.id AND w.id=$1 AND w.user_id=$2 AND i.symbol=$3',[watchlistId,userId,symbol]);return Boolean(r.rowCount)}
  async symbols(userId:string,watchlistId:string){const r=await this.pool.query('SELECT i.symbol FROM watchlist_items i JOIN watchlists w ON w.id=i.watchlist_id WHERE w.id=$1 AND w.user_id=$2 ORDER BY i.created_at',[watchlistId,userId]);return r.rows.map(x=>x.symbol)}
  async latestSnapshot(userId:string,symbol:string):Promise<(Quote&{id:string})|undefined>{const r=await this.pool.query('SELECT * FROM market_snapshots WHERE user_id=$1 AND symbol=$2 ORDER BY observed_at DESC LIMIT 1',[userId,symbol]);return r.rowCount?{...rowQuote(r.rows[0]),id:r.rows[0].id}:undefined}
  async saveSnapshot(userId:string,quote:Quote,client?:PoolClient){const q=client??this.pool;const r=await q.query('INSERT INTO market_snapshots(user_id,symbol,price,volume,volatility,market_updated_at,source,freshness_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[userId,quote.symbol,quote.price,quote.volume??null,quote.volatility??null,quote.updatedAt,'demo',quote.status]);return r.rows[0].id as string}
  async saveObservationAndEvent(userId:string,previous:{id:string}&Quote|undefined,current:Quote,change:Change){const c=await this.pool.connect();try{await c.query('BEGIN');const currentId=await this.saveSnapshot(userId,current,c);await c.query('INSERT INTO change_events(user_id,symbol,previous_snapshot_id,current_snapshot_id,price_change,percentage_change,volume_change,volatility_change,change_score,significance_level,explanation) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[userId,current.symbol,previous?.id??null,currentId,change.absolute,change.percent,change.volumePercent??null,change.volatilityPercent??null,change.score,change.level,change.explanation]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
  async changes(userId:string,symbol?:string){const r=await this.pool.query(`SELECT symbol,price_change,percentage_change,volume_change,volatility_change,change_score,significance_level,explanation,created_at FROM change_events WHERE user_id=$1 ${symbol?'AND symbol=$2':''} ORDER BY created_at DESC`,symbol?[userId,symbol]:[userId]);return r.rows}
}
