import express,{type Request,type Response,type NextFunction}from'express';import cors from'cors';import bcrypt from'bcryptjs';import jwt from'jsonwebtoken';import{MockMarketDataProvider}from'./demoProvider.js';import{detectChange,type Quote}from'./domain.js';import{PostgresRepository}from'./db.js';
type AR=Request<any,any,any,any>&{user?:{id:string;email:string}};const app=express(),provider=new MockMarketDataProvider(),db=process.env.DATABASE_URL?new PostgresRepository(process.env.DATABASE_URL):undefined,secret=process.env.JWT_SECRET||'demo-only-change-me';app.use(cors({origin:process.env.WEB_ORIGIN?.split(',')??true}));app.use(express.json({limit:'32kb'}));
const demoItems=new Set(['RELIANCE','TCS','INFY']);let demoSnapshots:Record<string,Quote>=Object.fromEntries([...demoItems].map(s=>[s,provider.quote(s)]));const route=(f:(q:AR,s:Response,n:NextFunction)=>Promise<unknown>)=>(q:AR,s:Response,n:NextFunction)=>void f(q,s,n).catch(n);
function auth(q:AR,s:Response,n:NextFunction){if(!db){q.user={id:'demo-user',email:'demo@pulse.local'};return n()}const h=q.header('authorization');if(!h?.startsWith('Bearer '))return s.status(401).json({error:'Authentication required'});try{q.user=jwt.verify(h.slice(7),secret,{issuer:'pulse'})as AR['user'];n()}catch{return s.status(401).json({error:'Invalid or expired token'})}}
const email=(x:unknown)=>typeof x==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x);const sign=(u:{id:string;email:string})=>jwt.sign(u,secret,{expiresIn:'8h',issuer:'pulse'});const name=(s:string)=>provider.catalog().find(x=>x.symbol===s)?.name??s;
async function card(uid:string,symbol:string){const current={...provider.quote(symbol),name:name(symbol)},previous=db?await db.latestSnapshot(uid,symbol):demoSnapshots[symbol];return{current,previous,change:detectChange(previous,current)}}async function cards(uid:string,id?:string){const symbols=db?await db.symbols(uid,id!):[...demoItems];return Promise.all(symbols.map(s=>card(uid,s)))}async function defaultId(uid:string){return db?(await db.defaultWatchlist(uid)).id:undefined}
async function add(uid:string,id:string|undefined,symbol:string){try{provider.quote(symbol)}catch{throw Object.assign(new Error('Unknown symbol'),{status:404})}if(db){if(!await db.addItem(uid,id!,symbol))throw Object.assign(new Error('This symbol is already on the watchlist'),{status:409});await db.saveSnapshot(uid,provider.quote(symbol))}else{if(demoItems.has(symbol))throw Object.assign(new Error('This symbol is already on the watchlist'),{status:409});demoItems.add(symbol);demoSnapshots[symbol]=provider.quote(symbol)}return card(uid,symbol)}
app.get('/api/health',(_,s)=>s.json({ok:true,mode:db?'postgres':'demo',provider:'mock'}));
app.post('/api/auth/register',route(async(q,s)=>{if(!db)return s.status(501).json({error:'Authentication is enabled when DATABASE_URL is configured'});const{email:e,password}=q.body??{};if(!email(e)||typeof password!=='string'||password.length<12)return s.status(400).json({error:'Use a valid email and password of at least 12 characters'});if(await db.findUser(e.toLowerCase()))return s.status(409).json({error:'An account already exists for this email'});const u=await db.createUser(e.toLowerCase(),await bcrypt.hash(password,12));await db.defaultWatchlist(u.id);s.status(201).json({token:sign(u),user:{id:u.id,email:u.email}})}));
app.post('/api/auth/login',route(async(q,s)=>{if(!db)return s.status(501).json({error:'Authentication is enabled when DATABASE_URL is configured'});const{email:e,password}=q.body??{};const u=email(e)&&typeof password==='string'?await db.findUser(e.toLowerCase()):undefined;if(!u||!await bcrypt.compare(password,u.passwordHash))return s.status(401).json({error:'Invalid email or password'});s.json({token:sign(u),user:{id:u.id,email:u.email}})}));
app.get('/api/watchlists',auth,route(async(q,s)=>s.json({watchlists:db?await db.listWatchlists(q.user!.id):[{id:'demo-watchlist',name:'My watchlist'}]})));
app.post('/api/watchlists',auth,route(async(q,s)=>{const n=String(q.body?.name??'').trim();if(!n||n.length>60)return s.status(400).json({error:'A watchlist name of up to 60 characters is required'});if(!db)return s.status(501).json({error:'Multiple watchlists require PostgreSQL'});s.status(201).json(await db.createWatchlist(q.user!.id,n))}));
app.delete('/api/watchlists/:id',auth,route(async(q,s)=>{if(!db)return s.status(501).json({error:'Demo watchlist cannot be deleted'});if(!await db.deleteWatchlist(q.user!.id,q.params.id))return s.status(404).json({error:'Watchlist not found'});s.status(204).end()}));
app.get('/api/watchlists/:id/items',auth,route(async(q,s)=>s.json({items:await cards(q.user!.id,q.params.id)})));
app.post('/api/watchlists/:id/items',auth,route(async(q,s)=>{try{s.status(201).json(await add(q.user!.id,q.params.id,String(q.body?.symbol??'').toUpperCase()))}catch(e){const x=e as Error&{status?:number};s.status(x.status??500).json({error:x.message})}}));
app.delete('/api/watchlists/:id/items/:symbol',auth,route(async(q,s)=>{const x=q.params.symbol.toUpperCase();const ok=db?await db.removeItem(q.user!.id,q.params.id,x):demoItems.delete(x);if(!ok)return s.status(404).json({error:'Watchlist item not found'});if(!db)delete demoSnapshots[x];s.status(204).end()}));
app.get('/api/watchlist',auth,route(async(q,s)=>s.json({items:await cards(q.user!.id,await defaultId(q.user!.id)),demo:{stage:provider.stage,mode:provider.mode}})));
app.post('/api/watchlist/:symbol',auth,route(async(q,s)=>{try{s.status(201).json(await add(q.user!.id,await defaultId(q.user!.id),q.params.symbol.toUpperCase()))}catch(e){const x=e as Error&{status?:number};s.status(x.status??500).json({error:x.message})}}));
app.delete('/api/watchlist/:symbol',auth,route(async(q,s)=>{const x=q.params.symbol.toUpperCase(),id=await defaultId(q.user!.id);const ok=db?await db.removeItem(q.user!.id,id!,x):demoItems.delete(x);if(!ok)return s.status(404).json({error:'Watchlist item not found'});if(!db)delete demoSnapshots[x];s.status(204).end()}));
app.get('/api/market/:symbol',auth,route(async(q,s)=>{try{s.json(await card(q.user!.id,q.params.symbol.toUpperCase()))}catch{s.status(404).json({error:'Unknown symbol'})}}));app.get('/api/market/:symbol/history',auth,route(async(q,s)=>{try{s.json(provider.history(q.params.symbol.toUpperCase()))}catch{s.status(404).json({error:'Unknown symbol'})}}));
app.get('/api/changes',auth,route(async(q,s)=>s.json({changes:db?await db.changes(q.user!.id):[]})));app.get('/api/changes/:symbol',auth,route(async(q,s)=>s.json({changes:db?await db.changes(q.user!.id,q.params.symbol.toUpperCase()):[]})));
app.post('/api/observe',auth,route(async(q,s)=>{const id=await defaultId(q.user!.id),symbols=db?await db.symbols(q.user!.id,id!):[...demoItems];for(const x of symbols){const current=provider.quote(x),previous=db?await db.latestSnapshot(q.user!.id,x):demoSnapshots[x],change=detectChange(previous,current);if(db)await db.saveObservationAndEvent(q.user!.id,previous as any,current,change);else demoSnapshots[x]=current}s.json({observedAt:new Date().toISOString()})}));
app.post('/api/demo/advance',(_,s)=>s.json({stage:provider.advance()}));app.post('/api/demo/mode/:mode',(q,s)=>{const m=q.params.mode as typeof provider.mode;if(!['healthy','stale','failure'].includes(m))return s.status(400).json({error:'Invalid demo mode'});provider.setMode(m);s.json({mode:m})});app.use((e:unknown,_q:Request,s:Response,_n:NextFunction)=>{console.error(e);s.status(500).json({error:'Unexpected server error'})});
async function start(){if(db)await db.migrate();app.listen(Number(process.env.PORT)||3001,()=>console.log(`PULSE API on http://localhost:${process.env.PORT||3001} (${db?'PostgreSQL':'Demo Mode'})`))}void start();export{app};
